---
# Composer project settings.
drupal_build_composer_project: false
drupal_build_composer: false
drupal_composer_dependencies: []

# Drupal install settings.
drupal_site_name: "Drupal"
drupal_core_path: "/var/www/drupal/web"
drupal_install_site: true
drupal_enable_modules: []

# Other overrides.
php_version: "7.2"
php_sendmail_path: "/usr/sbin/sendmail -t -i"
installed_extras:
  - drush

# Other secure defaults.
dashboard_install_dir: ""

# Restrict the firewall to only ports that are required for external services.
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
firewall_log_dropped_packets: true

ansible_python_interpreter: /usr/local/bin/python3
