---
# Composer project settings.
drupal_build_composer_project: false
drupal_build_composer: false
drupal_composer_dependencies: []

# Drupal install settings.
drupal_site_name: ""
drupal_core_path: "/var/www/drupal/web"
drupal_install_site: true
drupal_enable_modules:
  - admin_toolbar
  - admin_toolbar_tools
  - cog
  - config_update
  - features
  - features_ui
  - google_analytics
  - token
  - toolbar_anti_flicker
  - views
  - views_ui

#drupalvm_cron_jobs:
#  - name: "Drupal Cron"
#    minute: "*/15"
#    job: "{{ drush_path }} -r {{ drupal_core_path }} core-cron --quiet"

# Other overrides.
php_version: "7.1"
php_sendmail_path: "/usr/sbin/sendmail -t -i"
installed_extras:
  - drush

# Other secure defaults.
dashboard_install_dir: ''
apache_packages_state: installed

# Restrict the firewall to only ports that are required for external services.
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
firewall_log_dropped_packets: true

mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb