---
# Deploy from the project's Git repository.
drupal_deploy: true
drupal_deploy_accept_hostkey: true
drupal_deploy_repo: ""
drupal_deploy_dir: /var/www/drupal

# Set the domain for this site appropriately.
drupal_domain: ""
vagrant_hostname: "{{ drupal_domain }}"

# Only add the production docroot virtualhost.
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"